server:
  port: 8091

spring:
  data:
    mongodb:
      database: queckly
#      port: 27017
#      username: admin
#      password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org:
      springframework: INFO
