server:
  port: 8091

spring:
  data:
    mongodb:
      database: queckly
#      username: admin
#      password: adminq
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
